version: '3.9'

services:
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8082:8080"  # Puerto para acceder a Adminer desde el navegador
    volumes:
      - ./adminer-config/adminer-custom.php:/var/www/html/adminer.php  # Archivo PHP personalizado
      - ./adminer-config:/var/lib/adminer                # Persistencia de conexiones
    environment:
      ADMINER_DEFAULT_SERVER: db  # Conexión predeterminada al contenedor db
    networks:
      - php_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mysql_manager_phpmyadmin
    restart: always
    ports:
      - "8081:80"  # Acceso desde el puerto 8081 del host
    environment:
      PMA_HOST: db  # Nombre del servicio de MySQL (el contenedor 'db' en este caso)
      PMA_PORT: 3307
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}
    networks:
      - php_network  # Usamos la red personalizada

  db:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql  # Volumen para la persistencia de la base de datos
    ports:
      - "3307:3306"
    networks:
      - php_network  # Aseguramos que el contenedor de MySQL esté en la misma red

networks:
  php_network:
    driver: bridge
